<?php

namespace MainBundle\Repository;

/**
 * areaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class areaRepository extends \Doctrine\ORM\EntityRepository
{
}
