<?php

namespace MainBundle\Repository;

/**
 * tipomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipomRepository extends \Doctrine\ORM\EntityRepository
{
}
