<?php

namespace MainBundle\Repository;

/**
 * tratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tratamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
